version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image:
      postgres:14.3
    restart: always
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_ROOT_PASSWORD=${POSTGRES_ROOT_PASSWORD}
    ports:
      - "5432:5432"

  frontend:
    build:
      context: ./FE
      dockerfile: ../docker/frontend/Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "4200:80"
    depends_on:
      - backend
    command: ["nginx", "-g", "daemon off;"]
